---
# Source: vector-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-agent
  namespace: dev
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.11.0"
---
# Source: vector-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-agent
  namespace: dev
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.11.0"
data:
  # We leave `vector.toml` file name available to let externally managed config
  # maps to provide it.
  managed.toml: |
    # Configuration for vector.
    # Docs: https://vector.dev/docs/
    # Data dir is location controlled at the `DaemonSet`.
    data_dir = "/vector-data-dir"
    
    # Ingest logs from Kubernetes.
    [sources.kubernetes_logs]
      type = "kubernetes_logs"
      extra_label_selector = "vector.dev/include==true"

    # Inject topic from labels
    [transforms.inject_topic]
      type = "add_fields"
      inputs = ["kubernetes_logs"]
      overwrite = true
      fields.topic = "{{ kubernetes.pod_labels.vector\\.dev/topic }}"

    # Message to JSON
    [transforms.json]
      inputs = ["inject_topic"]
      type   = "json_parser"
      field  = "message"
      drop_field = true
      drop_invalid = false
      overwrite_target = true

    # Remove some fields
    [transforms.simplifier]
      type = "remove_fields"
      inputs = ["json"]
      fields = ["file", "kubernetes", "source_type", "stream", "timestamp"]

    # Kafka sink
    [sinks.kafka]
      type = "kafka"
      inputs = ["simplifier"]
      bootstrap_servers = "kafka-1:9092"
      compression = "none"
      healthcheck = true
      key_field = "time"
      topic = "{{ topic }}"
      encoding.codec = "json"
    
    # Emit internal Vector metrics.
    # [sources.internal_metrics]
    #   type = "internal_metrics"

    # Expose metrics for scraping in the Prometheus format.
    # [sinks.prometheus_sink]
    #   type = "prometheus"
    #   inputs = ["internal_metrics"]
    #   address = "0.0.0.0:9090"
---
# Source: vector-agent/templates/rbac.yaml
# Permissions to use Kubernetes API.
# Requires that RBAC authorization is enabled.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-agent
  namespace: dev
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
---
# Source: vector-agent/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-agent
  namespace: dev
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.11.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-agent
subjects:
  - kind: ServiceAccount
    name: vector-agent
    namespace: vector
---
# Source: vector-agent/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
  namespace: dev
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.11.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-agent
      app.kubernetes.io/instance: vector
  minReadySeconds: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 3dac4d3f040851abd23fb5bf6d48a5babbd001e35aaa5465fa23e45816918c14
      labels:
        app.kubernetes.io/name: vector-agent
        app.kubernetes.io/instance: vector
        vector.dev/exclude: "true"
    spec:
      serviceAccountName: vector-agent
      securityContext:
        {}
      containers:
        - name: vector
          securityContext:
            {}
          image: "timberio/vector:0.11.0-alpine"
          imagePullPolicy: "IfNotPresent"
          args:
            - --config
            - /etc/vector/*.toml
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            
            - name: LOG
              value: info
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {}
          volumeMounts:
            # Host log directory mount.
            - name: var-log
              mountPath: /var/log/
              readOnly: true
            # Host mount for docker and containerd log file symlinks.
            - name: var-lib
              mountPath: /var/lib
              readOnly: true
            # Vector data dir mount.
            - name: data-dir
              mountPath: "/vector-data-dir"
            # Vector config dir mount.
            - name: config-dir
              mountPath: /etc/vector
              readOnly: true
      terminationGracePeriodSeconds: 60
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        # Log directory.
        - name: var-log
          hostPath:
            path: /var/log/
        # Docker and containerd log files in Kubernetes are symlinks to this folder.
        - name: var-lib
          hostPath:
            path: /var/lib/
        # Vector will store it's data here.
        - name: data-dir
          hostPath:
            path: /var/lib/vector/
        # Vector config dir.
        - name: config-dir
          projected:
            sources:
              - configMap:
                  name: vector-agent
              - configMap:
                  name: vector-agent-config
                  optional: true
              - secret:
                  name: vector-agent-config
                  optional: true