---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: dev
  labels:
    app: mongo-express
spec:
  type: LoadBalancer
  ports:
    - port: 47017
      targetPort: 8081
  selector:
    app: mongo-express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: dev
  labels:
    app: mongo-express
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:0.54
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_OPTIONS_EDITORTHEME
              value: ambiance
          ports:
            - name: http
              containerPort: 8081
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "10m"
              memory: "32Mi"
