---
kind: Service
apiVersion: v1
metadata:
  name: echo-logger
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: echo-logger
  ports:
    - port: 49527
      targetPort: 9527

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-logger
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-logger
  template:
    metadata:
      labels:
        app: echo-logger
        vector.dev/include: "true"
        vector.dev/topic: "dev.echo"
    spec:
      containers:
        - name: echo-logger
          image: 36node/echo-logger
